![Algoritmos e Estrutura de Dados II - Prof Piva](AED2_banner.jpg)

## Aula 6 - Pilhas

### Primeira Implementação

In [5]:
# Implementacao da classe Pilha
class Stack:
    # Inicia com uma pilha vazia
    def __init__(self):
        self.itens = []
    
    # Verifica se pilha esta vazia
    def is_empty(self):
        return self.itens == []
    
    # Adiciona elemento no topo (topo e o final da lista)
    def push(self, item):
        self.itens.append(item)
        print(f"PUSH {item}")

    # Remove elemento do topo (final da lista)
    def pop(self):
        print(f"POP {Self.itens}")
        return self.itens.pop()
    
    # Obtem o elemento do topo (mas nao remove)
    def peek(self):
    # Em Python, indice -1 retorna ultimo elemento (topo)
        return self.itens[-1]
    
    # Retorna o numero de elementos da pilha
    def size(self):
        return len(self.itens)
    
    # Imprime pilha na tela
    def print_stack(self):
        print(self.itens)

In [24]:
# TESTANDO
s = Stack()

In [25]:
s.print_stack()

[]


In [26]:
s.push(1)

PUSH 1


In [27]:
s.push(2)

PUSH 2


In [31]:
s.push(3)

PUSH 3


In [34]:
s.print_stack( )

[1, 2, 3, 3]


In [37]:
s.pop( )

NameError: name 'Self' is not defined

In [41]:
s.pop( )

NameError: name 'Self' is not defined

In [39]:
s.print_stack()

[1, 2, 3, 3]


In [11]:
S.push(7)

PUSH 7


In [12]:
S.push(8)

PUSH 8


In [13]:
S.push(9)

PUSH 9


In [14]:
S.print_stack()

[1, 7, 8, 9]


In [15]:
print(S.is_empty())

False


### Segunda Implementação

In [44]:
import numpy as np

In [45]:
class Pilha:
    def __init__(self, capacidade):
        self.__capacidade = capacidade
        self.__topo = -1
        self.__valores = np.zeros(self.__capacidade, dtype=int)

    def __pilha_cheia(self):
        if self.__topo == self.__capacidade - 1:
            return True
        else:
            return False
    
    def __pilha_vazia(self):
        if self.__topo == -1:
            return True
        else:
            return False
    
    def empilhar(self, valor):
        if self.__pilha_cheia():
            print('A pilha está cheia')
        else:
            self.__topo += 1
            self.__valores[self.__topo] = valor
    
    def desempilhar(self):
        if self.__pilha_vazia():
            print('A pilha está vazia')
        else:
            self.__valores[self.__topo] = 0
            self.__topo -= 1
    
    def ver_topo(self):
        if self.__topo != -1:
            return self.__valores[self.__topo]
        else:
            return -1
    
    # Imprime pilha na tela
    def imprime_pilha(self):
        print(self.__valores)

In [46]:
pilha = Pilha(5)

In [47]:
pilha.imprime_pilha()

[0 0 0 0 0]


In [48]:
pilha.ver_topo()

-1

In [49]:
pilha.empilhar(1)
pilha.ver_topo()

np.int64(1)

In [50]:
pilha.empilhar(1)
pilha.empilhar(2)
pilha.empilhar(3)
pilha.empilhar(4)

In [51]:
pilha.imprime_pilha()

[1 1 2 3 4]


In [52]:
pilha.empilhar(6)

A pilha está cheia


In [53]:
pilha.ver_topo()

np.int64(4)

In [54]:
pilha.desempilhar()

In [55]:
pilha.ver_topo()

np.int64(3)

In [56]:
pilha.desempilhar()
pilha.desempilhar()
pilha.desempilhar()

In [57]:
pilha.ver_topo()

np.int64(1)

In [58]:
pilha.imprime_pilha()

[1 0 0 0 0]


In [59]:
pilha.desempilhar()

In [60]:
pilha.imprime_pilha()

[0 0 0 0 0]


In [61]:
pilha.desempilhar()

A pilha está vazia


# Vamos à Prática!
## Exercício

Utilização de pilhas para conversão de números inteiros em decimal para binário (método da divisão sucessiva por 2).

**Utilização do classe Stack..**

In [62]:
# Função que converte um número decimal para binário
def decimal_binario(numero):
 s = Stack()
 while numero > 0:
     resto = numero % 2
     s.push(resto)
     numero = numero // 2
 binario = ''
 while not s.is_empty():
     binario = binario + str(s.pop())
 return binario

### Testando!
233 --> binário

In [64]:
# TESTANDO
n = int(input('Entre com um número inteiro: '))
print(f"O valor {n} em binário é: {decimal_binario(n)}") 

Entre com um número inteiro:  352


PUSH 0
PUSH 0
PUSH 0
PUSH 0
PUSH 0
PUSH 1
PUSH 1
PUSH 0
PUSH 1


NameError: name 'Self' is not defined

### Fim Teoria Aula 6